ps_emailalerts.php

Fortunately, tables in database are exactly the same and do not require migration

Uninstall module used on PS 1.6 before using this one

---

views/templates/front/mailalerts-account-line.tpl

- Use icon instead uppercase X.
- Add title for accessibility.

Improve remove link

---

ps_emailalerts.php

This module has the same issue as in PaymentModule.php, total tax is wrong. Described here - https://github.com/PrestaShop/PrestaShop/issues/16227
This PR fixes it.

Fix total tax when using discounts

---

ps_emailalerts.php
views/templates/front/mailalerts-account.tpl
views/templates/hook/my-account-footer.tpl
views/templates/hook/my-account.tpl
views/templates/hook/product.tpl

Since version 1.7.6 of Prestashop, a new translation system has been implemented, which requires certain rules, especially for "Translation Domain". And since this "ps_emailalerts" module implements this new system, this commit fixes a few lines where the "Translation Domain" is badly written.

Adapt translation domains to the new translation system

---

controllers/front/actions.php

The email is casted as an int, so the query to remove the alert doesnt work properly when the user made an alert and later creates an account.
| Description?  | An email variable is casted as int when you try to remove an alert. It causes the alert not being removed if you did the alert as a Guest and then you try to remove it when you log in.
| Type?         | Bug fix
| BC breaks?    | Yes
| Deprecations? | No
| Fixed ticket? | No
| How to test?  |  Create an alert as a guest. Then create an account with the same email, and try to remove the alert.

Fix cast error when removing an Alert

---

MailAlert.php
ps_emailalerts.php

| Description?  | Old mail subject translations used Mail::l() which most of the times wouldn't save email subject and it wouldn't be translated correctly. This PR would fix this issue by replacing old mail subject translator with new.
| BC breaks?    | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#17096.
| How to test?  |  Install module, generate EmailsSubject.xlf file and check if new email subject translations appear.

Added new translator for email subjects

---

config.xml
ps_emailalerts.php

| Description?  | As per discussion on slack bumping the version to 2.2.2
| Fixed ticket? | nope.
| How to test?  | upgrade the module.
The milestone here lists everything that was done for 2.2.2: https://github.com/PrestaShop/ps_emailalerts/milestone/1?closed=1 
PM should also create 2.2.3 milestone and consider assigning the currently open issues / pr:s to milestones so that there is clear path forward.

Bump version to 2.2.2

---

ps_emailalerts.php

| Description?  | Module used to send nonsense emails for X combinations out of stock, when you deleted a product. A simple fix to check if the product actually exist will fix it. `$product->active == 1` is not enough, because even an empty Product object has default active set to true.
| Fixed ticket? | Fixes PrestaShop/Prestashop#9641
| How to test?  | Install this module, enable sending out of stock emails, set treshold to 3. Create product with 2 combinations. Set  one combination quantity to 10, second combination to 1. You should receive email about low stock. Go delete the product, you should receive no email.

Fix sending out of stock alerts for products being deleted

---

ps_emailalerts.php

| Description?  | This PR fixes wrong logic when displaying ordered customized products.
| Fixed ticket? | Fixes PrestaShop/Prestashop#16551
| How to test?  | https://github.com/PrestaShop/PrestaShop/issues/16551#issue-528763521
Old branch got messed up so opening a PR.
I will need to check if this solution still works fine, I just copied data from old branch.
Ping @kpodemski

Fix product customization logic in the listing

---

composer.json
composer.lock

| Description?  | because `prestashop/php-dev-tools` was not in the `require-dev` dependencies, it was taken into account when trying to require it on PrestaShop 8.0, but the php compatibility was causing an issue. This PR solves the issue by putting `prestashop/php-dev-tools` in the `require-dev` dependencies.
| Fixed ticket? | Fixes PrestaShop/Prestashop#27037
| How to test?  | No test needed?

Move php-dev-tools to require-dev

---

controllers/front/account.php

| Description?  | Last key of breadcrumbs was missing on page in my account section.
| Fixed ticket? | no
| How to test?  | Check the page before and after.

Add last key of breadcrumbs

---

config.xml
ps_emailalerts.php
tests/php/phpstan/phpstan.neon

| Description?  | In some cases, Symfony container wasn't properly initialized in the front office
| Type?         | critical
| Fixed ticket? | n/a
| How to test?  | The instruction is below
1. Make sure you have `ps_emailalerts` installed
2. Install the module from the attachment
3. Visit the configuration of the `testcontainer` module before, and after this PR
[testcontainer.zip](https://github.com/PrestaShop/ps_emailalerts/files/7973636/testcontainer.zip)
The origin of the error is that they're loading `init.php` file in their module on the top of the file, this is causing some misbehavior while loading the container. This check that has been …

Fix an issue with kernel container in some payment modules

---

views/templates/hook/product.tpl

… bootstrap newer than 4 alpha 4.
| Description?  | Removing a CSS-class, that is useless in classic theme, but creates a compatibility issue with themes based on Bootstrap newer than 4 beta 4. See https://github.com/PrestaShop/PrestaShop/issues/28216#issuecomment-1094772517
| Fixed ticket? | Fixes PrestaShop/Prestashop#28216
| How to test?  | As a customer subscribe to a product notification using `classic` theme, and using a them based on a newer bootstrap (e.g. `classic-rocket`).

Remove class unused in classic theme, but breaking comp with BS4

---

views/templates/front/mailalerts-account-line.tpl
views/templates/front/mailalerts-account.tpl

| Description?  | This improves the display of the list of notifications in the customer account: fixes alignment and margin issues. 
| Fixed ticket? | Fixes PrestaShop/Prestashop#28217.
| How to test?  | Using this branch, go on the list of notifications page in FO see if everything looks fine

Display of list of notifications in my account

---

ps_emailalerts.php
views/templates/hook/product.tpl

| Description?  | Display an info alert if the customer has already subscribed to the product notifications.
| Fixed ticket? | Fixes PrestaShop/Prestashop#28218.
| How to test?  | As a customer subscribe to a product notification. Display the product page again. There is an info alert.

Display an info alert if the customer has already subscribed.

---

controllers/front/actions.php

| Description?  | This replaces the old translations domains of `Modules.Mailalerts` with the current ones `Modules.Emailalerts`
| Type?         | refacto
| Fixed ticket? | Fixes PrestaShop/PrestaShop#17810
| How to test?  | Inspect the code. As the wrong translations domains do not cause a bug in FO, there is not a specific test.

Rename incorrect translation domains.

---

ps_emailalerts.php
upgrade/upgrade-2.4.1.php

| Description?  | Since PrestaShop 1.7.8 seems to be required to implement the hook `registerGDPRConsent` hook and an empty listener `HookRegisterGDPRConsent`, otherwise the module is not psgdpr module compliant. This PR fix the compatibility of ps_emailalerts.
| Fixed ticket? | Fixes PrestaShop/Prestashop#30379
| How to test?  | Fresh install of latest PS 1.7.8 or PS 8.0 or PS 8.1, the module is not showed in the psgdpr module, and the gdpr checkbox are not displayed in the product page. This PR fix it. Follow PrestaShop/Prestashop#30379 for more details

Fix compatibility with psgdpr and ps >=1.7.8

---

ps_emailalerts.php

| Description?  | With normal or combination products, if product or one of the combination is out-of-stock and I edit the product, everytime I save it, I'll receive an email.
| Fixed ticket? | Fixes PrestaShop/Prestashop#25981
| How to test?  | Install both this and related PR. Enable notifications for out of stock products in email alerts. Create a product with combinations, set quantity of all of them below the treshold. See that every time you save product, it sends you many emails. With these PRs, it's fixed.
Related PR: https://github.com/PrestaShop/PrestaShop/pull/25984
If module will be used on older PS, it will …

Do not send out emails if quantity did not change

---

MailAlert.php
controllers/front/actions.php

| Description?  | There are some duplication and inconsistency with typecasting in ps_emailalerts module v2.4.0. <br>Please check details in the Fixed ticket.
| Deprecations? |  no
| Fixed ticket? | Fixes PrestaShop/Prestashop#30481
| How to test?  | Check PR's 4 commits one by one is the best way (with a dev :).<br> Further check module Configuration in BO to make sure nothing is broken.

Symplify typecast

---

controllers/front/actions.php

| Description?  | When a user isn't logged in and typed an unknown email address, we can't add this email address to database with this error `Customer id can't be empty`.
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/32037
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/32037

Fix add action customer id

---

MailAlert.php

| Description?  | Sending of notification could accidentally switch shop and language context. This is fixed now. We also send only notifications in shops that share the stock. It would be useless to trigger hookActionUpdateQuantity in shops that do not share stock.
| Fixed ticket? | Fixes PrestaShop/Prestashop#30187
| How to test?  | See [#30187](https://github.com/PrestaShop/PrestaShop/issues/30187) for the steps to reproduce the issue. After this PR, there is no longer any confusion of shops or languages.

We must not switch context (shop and language)

---

ps_emailalerts.php

| Description?  | Avoid 4 lines of --- when customization
| Fixed ticket? | 
| How to test?  | Place an order with a product with customization, check alert email received for the new order and there aren't 4 lines of --- at the end of each product with customization

Avoid 4 lines of --- when customization

---

ps_emailalerts.php

| Description?  | This PR will remove a file that is included by registerStylesheet that doesn't exists anymore. It's a refuse.
| Type?         | refacto

Removed unused stylesheet that doesn't exists anymore

---

js/mailalerts.js

| Description?  | The “>” selector makes it impossible to customize this module, particularly as we can't add any other HTML element between the “.js-mailalert” div and the input[type=email]. </br>By removing this selector, we can add HTML elements between them and maintain the current functionality.
| Type?         |improvement
| BC breaks?    |no
| Deprecations? |no
| Fixed ticket? | /
| How to test?  |Remove the “>” selector in the file and test operation

Remove the “>” selector to make the selector more flexible
